# Generated by Django 5.0.4 on 2024-04-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='activiti',
            field=models.BooleanField(default=True),
        ),
    ]
