# Generated by Django 5.0.4 on 2024-04-05 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_activiti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, default=datetime.datetime(2024, 4, 5, 21, 6, 40, 648421, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
